sudo: required

language: python

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` -o docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /bin/
  - sudo apt-get update
  - sudo apt-get install software-properties-common
  - sudo apt-add-repository ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get install ansible
  
install:
  - pip install coveralls
  - pip install coverage
  - pip install nose
  
script:
    - docker version
    - docker-compose version
    - python .convert.py .
    - cd .site && ./build.sh

deploy:
  # teardown old infrustructure
  - provider: script
    script: bash .site/ansible-aws-ec2/teardown.sh
    on:
      branch: master
  # deploy master to production
  - provider: script
    script: bash .site/ansible-aws-ec2/deploy.sh
    on:
      branch:  master
