sudo: required

os:
  - linux

dist: trusty
#language: python

services:
  - docker

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - curl -L https://github.com/docker/compose/releases/download/1.22.0/docker-compose-`uname -s`-`uname -m` -o docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /bin/
  - sudo apt-get update
  - sudo apt-get -y install software-properties-common
  - sudo apt-add-repository -y ppa:ansible/ansible
  - sudo apt-get update
  - sudo apt-get -y install ansible 
  - sudo pip install --upgrade pip
  
install:
  - sudo pip install coveralls
  - sudo pip install coverage
  - sudo pip install nose
  - sudo pip install boto3 
  - sudo pip install urllib3[secure]
  - sudo ansible-galaxy install -r .site/ansible-aws-ec2/requirements.yml
  
script:
  - docker version
  - docker-compose version
  - python .convert.py .
  - cd .site && ./build.sh 
  - cd ansible-aws-ec2

deploy:
  # teardown old infrustructure
  - provider: script
    skip_cleanup: true
    script: bash teardown.sh
    on:
      branch: master
  # deploy master to production
  - provider: script
    skip_cleanup: true
    script: bash deploy.sh
    on:
      branch:  master
